/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-18 at 23:06:41 UTC 
 * Modify at your own risk.
 */

package com.appspot.willisaj_movie_match.moviematch.model;

/**
 * Model definition for AccountProtoUserNamePasswordEmailWillShare.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the moviematch. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AccountProtoUserNamePasswordEmailWillShare extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_name")
  private java.lang.String userName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean willShare;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public AccountProtoUserNamePasswordEmailWillShare setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public AccountProtoUserNamePasswordEmailWillShare setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public AccountProtoUserNamePasswordEmailWillShare setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getWillShare() {
    return willShare;
  }

  /**
   * @param willShare willShare or {@code null} for none
   */
  public AccountProtoUserNamePasswordEmailWillShare setWillShare(java.lang.Boolean willShare) {
    this.willShare = willShare;
    return this;
  }

  @Override
  public AccountProtoUserNamePasswordEmailWillShare set(String fieldName, Object value) {
    return (AccountProtoUserNamePasswordEmailWillShare) super.set(fieldName, value);
  }

  @Override
  public AccountProtoUserNamePasswordEmailWillShare clone() {
    return (AccountProtoUserNamePasswordEmailWillShare) super.clone();
  }

}
