/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-18 at 23:06:41 UTC 
 * Modify at your own risk.
 */

package com.appspot.willisaj_movie_match.moviematch.model;

/**
 * Model definition for GenrePreferenceProtoGenreNameAccountKey.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the moviematch. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GenrePreferenceProtoGenreNameAccountKey extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("account_key")
  private java.lang.String accountKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("genre_name")
  private java.lang.String genreName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccountKey() {
    return accountKey;
  }

  /**
   * @param accountKey accountKey or {@code null} for none
   */
  public GenrePreferenceProtoGenreNameAccountKey setAccountKey(java.lang.String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGenreName() {
    return genreName;
  }

  /**
   * @param genreName genreName or {@code null} for none
   */
  public GenrePreferenceProtoGenreNameAccountKey setGenreName(java.lang.String genreName) {
    this.genreName = genreName;
    return this;
  }

  @Override
  public GenrePreferenceProtoGenreNameAccountKey set(String fieldName, Object value) {
    return (GenrePreferenceProtoGenreNameAccountKey) super.set(fieldName, value);
  }

  @Override
  public GenrePreferenceProtoGenreNameAccountKey clone() {
    return (GenrePreferenceProtoGenreNameAccountKey) super.clone();
  }

}
