/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-18 at 23:06:41 UTC 
 * Modify at your own risk.
 */

package com.appspot.willisaj_movie_match.moviematch.model;

/**
 * Model definition for WishlistMovieProtoMovieNameMovieIdAccountKey.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the moviematch. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class WishlistMovieProtoMovieNameMovieIdAccountKey extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("account_key")
  private java.lang.String accountKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("movie_id")
  private java.lang.String movieId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("movie_name")
  private java.lang.String movieName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccountKey() {
    return accountKey;
  }

  /**
   * @param accountKey accountKey or {@code null} for none
   */
  public WishlistMovieProtoMovieNameMovieIdAccountKey setAccountKey(java.lang.String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMovieId() {
    return movieId;
  }

  /**
   * @param movieId movieId or {@code null} for none
   */
  public WishlistMovieProtoMovieNameMovieIdAccountKey setMovieId(java.lang.String movieId) {
    this.movieId = movieId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMovieName() {
    return movieName;
  }

  /**
   * @param movieName movieName or {@code null} for none
   */
  public WishlistMovieProtoMovieNameMovieIdAccountKey setMovieName(java.lang.String movieName) {
    this.movieName = movieName;
    return this;
  }

  @Override
  public WishlistMovieProtoMovieNameMovieIdAccountKey set(String fieldName, Object value) {
    return (WishlistMovieProtoMovieNameMovieIdAccountKey) super.set(fieldName, value);
  }

  @Override
  public WishlistMovieProtoMovieNameMovieIdAccountKey clone() {
    return (WishlistMovieProtoMovieNameMovieIdAccountKey) super.clone();
  }

}
